lib/rowgame_web/router.ex
defmodule RowgameWeb.Router do
  use RowgameWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]    
  end

  # adapted from nat's notes
  # http://www.ccs.neu.edu/home/ntuck/courses/2018/01/cs4550/notes/12-microblog/notes.html
  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Rowgame.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  scope "/", RowgameWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/game/:game", PageController, :game
    resources "/users", UserController
    resources "/games", GameController

    post "/session", SessionController, :create
    delete "/session", SessionController, :delete

  end

  scope "/api/v1", RowgameWeb do
    pipe_through :api
    resources "/moves", MoveController, except: [:new, :edit]
    resources "/chats", ChatController, except: [:new, :edit]
  end
end

lib/rowgame_web/views/layout_view.ex
defmodule RowgameWeb.LayoutView do
  use RowgameWeb, :view
end

lib/rowgame_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Rowgame!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <%= if @current_user do %>
      <script>
       window.current_user_id = <%= @current_user.id %>;
       window.current_user_name = "<%= @current_user.username %>";
      </script>
    <% else %>
      <script>
       window.current_user_id = -1;
       window.current_user_name = "None";
      </script>
    <% end %>
  </head>

  <body>
    <div class="container">
      <!-- header adapted from nat's notes -->
      <!-- http://www.ccs.neu.edu/home/ntuck/courses/2018/01/cs4550/notes/12-microblog/notes.html -->
      <div class="row">
	<%= if @current_user do %>
	  <div class="col-5 offset-7">
	    <p>
	      Logged in as: <%= @current_user.username %> |
	      <%= link "Your Profile", to: user_path(@conn, :show, @current_user) %> |
	      <%= link "Show Games", to: game_path(@conn, :index) %> |
	      <%= link "Log Out", to: "/session", method: :delete %>
	    </p>
	  </div>
	<% else %>
	  <div class="col-2 offset-10">
	    Not logged in. |
	    <%= link "Log In", to: page_path(@conn, :index) %>
	  </div>
	<% end %>
      </div>

      
      <%= if get_flash(@conn, :info) do %>
	<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
	<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>